### ISSUE TITLE
Speaker links ignored

### ISSUE THREAD

**Issue by pazz** [DigitaleGesellschaft/jekyll-theme-conference#10]
I have one more for you:
When you generate the demo page using the data from the repository, the links attached to speakers in their yml files are ignored:

person-a.md
```yaml
---
name: Tolga Philip
first_name: Tolga
last_name: Philip
links:
  - name: Profile
    href: https://github.com
---
```

yet the speaker page contains this

```html
    <h5 class="mt-4 mb-1">More Information:</h5>

    <ul class="list-unstyled">
      
        
        

        
          <li class="mb-1 ml-2 pl-2 border-soft-primary">
            <a class="text-reset" href="XXX" title="Profile">
              Profile
            </a>
          </li>
        
      
    </ul>
```

where XXX is the value of the last (absolute) url listed under my page wide links

```yaml
 navigation:
    links:
      - name: Program
        disabled: false
        relative_url: /program/
      - name: Talks
        disabled: true
        relative_url: /talks/
      - name: Speakers
        disabled: false
        relative_url: /speakers/
      - name: Previous Editions
        menu:
          - name: foo
            absolute_url: YYY
          - name: bar
            absolute_url: XXX
```
