### ISSUE TITLE
program: initial full hour is missing?

### ISSUE THREAD

**Issue by pazz** [DigitaleGesellschaft/jekyll-theme-conference#9]
I am missing the inital full hour in the program, but not with the demo program from the repo.

This is using version `3.0.3` from the gem, as installed with `bundle`.
Any ideas?

![2021-01-28-170433_1381x1402_scrot](https://user-images.githubusercontent.com/628455/106172641-f04ea880-618a-11eb-9de2-37639e2b989b.png)

this is my program.yml.
```yaml
days:
- abbr: Tue
  date: '2021-03-30'
  name: Tuesday
  rooms:
  - name: Tuesday
    talks:
      - name: Logic and Learning in Network Cascades
        time_start: '13:30'
        time_end: '14:00'
      - name: A non-trivial polynomial time algorithm for a 3D Stable Roommates problem
        time_start: '14:00'
        time_end: '14:30'
      - name: Relative Error Streaming Quantiles
        time_start: '14:30'
        time_end: '15:00'
```
